### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by 983** [poppinace/indexnet_matting#16]
Thank you for this amazing repository!

I tried to find out the license, but I am confused because there are several different ones.

- The top-level license is MIT: https://github.com/poppinace/indexnet_matting/blob/master/LICENSE.md
- The license of most code is a modification of the 2-Clause BSD license which disallows all use except academic use: https://github.com/poppinace/indexnet_matting/blob/867720dee1bc74212ec77bf2ad1c43af3bbc1c8f/scripts/hlmobilenetv2.py#L11
- There is the Adobe license: https://github.com/poppinace/indexnet_matting/blob/master/Adobe%20Deep%20Image%20Mattng%20Dataset%20License%20Agreement.pdf

So my question is: What is the license of the code?

**Comment by poppinace** [comment]
Hi,
If I understand the lisense right, the code is only covered by the MIT license. It only allows academic use. The pre-trained model instead is covered by both the MIT and the Adobe license.

**Comment by 983** [comment]
If you add additional restrictions like "academic purpose only", it's not the MIT license anymore and you should probably choose a different name to avoid confusion.

Most people won't expect additional restrictions when they read the MIT license:

> Permission is hereby granted [...] to deal in the Software without restriction [...]

Also I am not sure about the model license. Usually, when something has multiple licenses, you can [choose which one you want to abide by](https://en.wikipedia.org/wiki/Multi-licensing), but that is probably not intended here, since you can't lift the restrictions of the Adobe license. Applying both licenses at once does not make sense either because the licenses contradict each other.

**Comment by InternetMaster1** [comment]
What are the steps for commercial licensing?

**Comment by 983** [comment]
The license has been updated to clarify that the code may only be utilized for academic purposes.
