### ISSUE TITLE
Inquiry about the supplementary material

### ISSUE THREAD

**Issue by wuyujack** [poppinace/indexnet_matting#2]
Hi,

Great work and I am looking forward to the release of training code. By the way, would you like to share the supplementary material of the original paper in this Github? I am really interested in the performance of other visual tasks using IndexNet as announced in Section 5.4.

Regards,
Mingfu

**Comment by poppinace** [comment]
Hi Mingfu,

Thank you for your interests. The Supp. has been added. I'll close this issue.

Hao
