### ISSUE TITLE
Questions about B11 model

### ISSUE THREAD

**Issue by kfeng123** [poppinace/indexnet_matting#21]
Thank you for your great work!

I have two questions regarding your B11 model (Unet).
(1) It seems that your code uses both conv and pooling for downsampling, which maybe a typo? So which downsampling module do you use?
(2) Is the crop size 320 or 321 in your training of B11?

**Comment by poppinace** [comment]
@kfeng123 Hi, for your question:
(1) I only use pooling. I have changed 2-stride conv to be 1-stride in B11.
(2) 320

**Comment by kfeng123** [comment]
Thank you!
