### ISSUE TITLE
train on multi gpu

### ISSUE THREAD

**Issue by QWERDF007** [poppinace/indexnet_matting#24]
How to train on multi gpu? thanks

**Comment by poppinace** [comment]
Hi, the code is compatible on multi GPU training.
Just set CUDA_VISIBLE_DEVICES=0,1,2,3 if you have 4 GPUs and set sync_bn = True.

**Comment by QWERDF007** [comment]
thanks!

**Comment by QWERDF007** [comment]
Do i need to change batc size?
