### ISSUE TITLE
about the evaluation code

### ISSUE THREAD

**Issue by wrrJasmine** [poppinace/indexnet_matting#3]
@poppinace 
hi 
Thank you for your great work
You mentioned you have implemented a python version of the evaluation_code. But I can't find it in the folder.  Would you mind to tell me where is it?

**Comment by wrrJasmine** [comment]
@poppinace 
I have one more question. In the line 787 of hlmobilenetv2.py, it is the first layer of mobilenetv2 and you set the stride 1 followed with a maxpooling layer instead of stride=2, so that there is one more unpooling layer in the decoder part. Is it matters to the final results?

**Comment by poppinace** [comment]
Hi @wrrJasmine ,

The python evaluation code in in the `scripts/utils.py`

As for the second question, the maxpooling and unpooling layers in mobilenetv2 are introduced to make a direct comparison to the SegNet-based Deep Matting. It matters to the final results. In paper we have reported the numeral results when unpooling is disabled. Please have a look.

**Comment by wrrJasmine** [comment]
@poppinace 
I got it. Thank you so much!

**Comment by wrrJasmine** [comment]
@poppinace 
hi！
I found that one of the trimap in my test forder is much more different from the other 19 trimaps. the name is "girl-1467820_1280_12.png". It is all gray. I am not sure if it is my fault to mix it. would you mind to check it in your test folder?

**Comment by poppinace** [comment]
I also noticed this issue.
The testing trimaps are not generated by code but are provided by the original authors.
Maybe you can drop them an e-mail enquiring this.
