### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by wukaoliu** [poppinace/indexnet_matting#5]
When will your evaluation code of python version be made public?

**Comment by poppinace** [comment]
@wukaoliu the python evaluation code is in the file utils.py

**Comment by wukaoliu** [comment]
Thanks for your reply. 




            
            
                
                    
                            
                                
                            
                            
                                yuhao liu
                            
                    
                        
                            
                                    邮箱：yuhaoliu7456@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 10/14/2019 07:44, Hao Lu wrote: @wukaoliu the python evaluation code is in the file utils.py

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/poppinace/indexnet_matting/issues/5?email_source=notifications\u0026email_token=AKXCWCTIWF4YP37ZZCOQHF3QOOXFPA5CNFSM4I7MDSOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBDDDEQ#issuecomment-541471122",
"url": "https://github.com/poppinace/indexnet_matting/issues/5?email_source=notifications\u0026email_token=AKXCWCTIWF4YP37ZZCOQHF3QOOXFPA5CNFSM4I7MDSOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBDDDEQ#issuecomment-541471122",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
