### ISSUE TITLE
indexnet_matting.pth.rar open error

### ISSUE THREAD

**Issue by luoqiuluoqiu** [poppinace/indexnet_matting#6]

**Comment by luoqiuluoqiu** [comment]
---------------------------
错误
---------------------------
D:\workplace\tcpython\LT\indexnet_matting\pretrained\indexnet_matting.pth.rar
这个压缩文件格式未知或者数据已经被损坏
---------------------------
确定   
---------------------------

**Comment by poppinace** [comment]
Hi @luoqiuluoqiu ,

Please do not unzip the model file. You can run the demo following the instruction.
