### ISSUE TITLE
pretrained模型基于pytorch1.3  支持移动端

### ISSUE THREAD

**Issue by arixlin** [poppinace/indexnet_matting#7]
您好，你们的模型参数非常少，非常适合移动端部署，是否可以提供基于pytorch 1.3训练的模型， 目前这个模型无法在移动端进行使用， 谢谢！

**Comment by poppinace** [comment]
Sorry, I cannot type Chinese in my Linux system.
I am afraid your request is out of the scope of research issues. My apologies.

**Comment by arixlin** [comment]
@poppinace Thanks！
